### ISSUE TITLE
Why is "requests" versioned?

### ISSUE THREAD

**Issue by davies-w** [0x7d4/syncedlyrics#10]
Hi, thanks for this awesome tool. However, when I installed it on colab, it had a conflict with the version of requests that google colab has installed. Is there any reason to have such a strict upper bound (3.0.0?)

requests<3.0.0,>=2.28.1

**Comment by davies-w** [comment]
Ah, it turns out that its the lower bound that's the issue. Google colab has 2.27.1 installed.

https://i.imgur.com/Q9jZ1zw.png

I guess there is still the question, is 2.28.1 the minimum viable version?

**Comment by Vuizur** [comment]
I think the lower/upper bounds are simply a consequence of installing the dependencies with `poetry add <library>`, which adds these limits by default. So there shouldn't be a problem with downgrading them. 

If you need it urgently, you could also fork this repo, make the changes and install it with pip install git+<url-of-fork>.
